modLoader="javafml"
loaderVersion="[47,)"

license="MIT"

[[mods]]
modId="offhandblocker"
version="1.0.0"
displayName="offhandblocker"
authors="ashpapi"
description=''

[[dependencies.offhandblocker]]
modId="forge"
mandatory=true
versionRange="[47.3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.offhandblocker]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
